<?php
namespace DumpLib;

use DumpLib\Utils\Kind;

class DumpLib
{
    const DEFAULT_THEME = Themes\HowionBlack\HowionBlack::class;

    public $theme;

    public function __construct(Themes\Theme $theme = null)
    {
        // INIT THEME
        $this->initializeTheme($theme);
    }

    public function cleanPreviousDumps()
    {
        $this->theme->cleanPreviousDumps();
    }

    public function dump(...$values)
    {
        // PASS OBJECTS TO THEME
        foreach ($values as $val) $this->theme->dump($val, Kind::resolve($val));
    }

    public function dd(...$values)
    {
        // DUMP N DIE
        $this->dump(...$values);
        $this->deliver(true);
    }

    public function deliver($die = false)
    {
        // GET GENERATED HTML OR FALSE ON NO-DUMP SITUATION
        $html = $this->theme->htmlCode();

        if ($html !== false)
        {
            // CLEAN CURRENT OUTPUT BUFFER
            ob_clean();

            // PRINT HTML GENERATED BY THEME
            echo $html;

            // STOP EXECUTION
            if ($die) exit(0);

            // YEY
            return true;
        }
        else
        {
            return false;
        }
    }

    protected function initializeTheme($theme)
    {
        // RETURN DEFAULT THEME IF GIVEN VALUE IS NULL
        if (is_null($theme) || !($theme instanceof Themes\Theme))
        {
            $class = static::DEFAULT_THEME;
            $this->theme = new $class;
        }
        else
        {
            $this->theme = $theme;
        }
    }
}
